wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.5
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: val_loss
      5: 1
      6:
      - 1
    - 1: val_acc
      5: 1
      6:
      - 1
    python_version: 3.8.10
    start_time: 1634714011
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      2:
      - 1
      - 5
      - 9
      - 11
      3:
      - 7
      4: 3.8.10
      5: 0.12.5
      6: 4.5.1
      8:
      - 5
lr:
  desc: null
  value: 0.01
model_name:
  desc: null
  value: google/bert_uncased_L-2_H-128_A-2
